server:
  port: 8095
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver01:8093/eureka/
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
    appname: enreka-client
spring:
  application:
    # 对应的Config Server的配置文件对应的application
    name: enreka-client