server:
  port: 8093
eureka:
  instance:
    preferIpAddress: true
    hostname: eurekaserver01
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #关闭自我保护模式
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000