server:
  port: 8090
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: true
        git:
          uri: https://github.com/sunjiaqing/spring-cloud-config/
          username:
          password:
          #searchPaths: searchPaths-demo,dmeo*,*
encrypt:
  key-store:
   location: classpath:/server.jks
   password: letmein
   alias: mytestkey
   secret: changeme